# CodeRabbit 설정
language: ko

reviews:
  auto_review:
    enabled: true
    drafts: false
    # 모든 브랜치에서 리뷰
    base_branches:
      - main
      - dev
      - develop
      - master
      - "feature/.*"
      - "fix/.*"
      - "test/.*"
      - "docs/.*"

  # 프로파일
  profile: chill

  # 리뷰 옵션
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  # 파일 필터
  path_filters:
    - "**/*.java"
    - "**/*.py"
    - "**/*.gradle"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.md"
    - "**/*.json"

  # 제외 파일
  path_ignore:
    - "**/node_modules/**"
    - "**/build/**"
    - "**/dist/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/data/chroma_*/**"        # ChromaDB 제외
    - "**/chroma.sqlite3"          # SQLite 파일 제외
    - "**/data/raw/**"

  # 파일별 지침
  path_instructions:
    - path: "**/*.py"
      instructions: |
        Python 코드 리뷰:
        - PEP 8 스타일 가이드 준수
        - 타입 힌팅 확인
        - Docstring 작성
        - 에러 핸들링

    - path: "**/*.java"
      instructions: |
        Java 코드 리뷰:
        - Spring Boot 베스트 프랙티스
        - 보안 취약점 체크

chat:
  auto_reply: true

early_access: false
enable_free_tier: true
